export const cardContent = [
  {
    title: "design-system",
    type: "Public",
    lang: "React",
    size: "7320 KB",
    date: "Updated 1 day ago",
  },
  {
    title: "codeant-ci-app",
    type: "Private",
    lang: "Javascript",
    size: "5871 KB",
    date: "Updated 2 days ago",
  },
  {
    title: "analytics-dashboard",
    type: "Private",
    lang: "Python",
    size: "4521 KB",
    date: "Updated 5 days ago",
  },
  {
    title: "mobile-app",
    type: "Public",
    lang: "Swift",
    size: "3096 KB",
    date: "Updated 3 days ago",
  },
  {
    title: "e-commerce-platform",
    type: "Private",
    lang: "Java",
    size: "6210 KB",
    date: "Updated 6 days ago",
  },
  {
    title: "blog-website",
    type: "Public",
    lang: "HTML/CSS",
    size: "1876 KB",
    date: "Updated 4 days ago",
  },
  {
    title: "social-network",
    type: "Private",
    lang: "PHP",
    size: "5432 KB",
    date: "Updated 7 days ago",
  },
  {
    title: "personal-portfolio",
    type: "Private",
    lang: "NextJS",
    size: "7320 KB",
    date: "Updated 15 day ago",
  },
  {
    title: "design-system",
    type: "Public",
    lang: "React",
    size: "7320 KB",
    date: "Updated 1 day ago",
  },
  {
    title: "codeant-ci-app",
    type: "Private",
    lang: "Javascript",
    size: "5871 KB",
    date: "Updated 2 days ago",
  },
  {
    title: "analytics-dashboard",
    type: "Private",
    lang: "Python",
    size: "4521 KB",
    date: "Updated 5 days ago",
  },
  {
    title: "mobile-app",
    type: "Public",
    lang: "Swift",
    size: "3096 KB",
    date: "Updated 3 days ago",
  },
  {
    title: "e-commerce-platform",
    type: "Private",
    lang: "Java",
    size: "6210 KB",
    date: "Updated 6 days ago",
  },
  {
    title: "blog-website",
    type: "Public",
    lang: "HTML/CSS",
    size: "1876 KB",
    date: "Updated 4 days ago",
  },
  {
    title: "social-network",
    type: "Private",
    lang: "PHP",
    size: "5432 KB",
    date: "Updated 7 days ago",
  },
  {
    title: "personal-portfolio",
    type: "Private",
    lang: "NextJS",
    size: "7320 KB",
    date: "Updated 15 day ago",
  },
  {
    title: "design-system",
    type: "Public",
    lang: "React",
    size: "7320 KB",
    date: "Updated 1 day ago",
  },
  {
    title: "codeant-ci-app",
    type: "Private",
    lang: "Javascript",
    size: "5871 KB",
    date: "Updated 2 days ago",
  },
  {
    title: "analytics-dashboard",
    type: "Private",
    lang: "Python",
    size: "4521 KB",
    date: "Updated 5 days ago",
  },
  {
    title: "mobile-app",
    type: "Public",
    lang: "Swift",
    size: "3096 KB",
    date: "Updated 3 days ago",
  },
  {
    title: "e-commerce-platform",
    type: "Private",
    lang: "Java",
    size: "6210 KB",
    date: "Updated 6 days ago",
  },
  {
    title: "blog-website",
    type: "Public",
    lang: "HTML/CSS",
    size: "1876 KB",
    date: "Updated 4 days ago",
  },
  {
    title: "social-network",
    type: "Private",
    lang: "PHP",
    size: "5432 KB",
    date: "Updated 7 days ago",
  },
  {
    title: "personal-portfolio",
    type: "Private",
    lang: "NextJS",
    size: "7320 KB",
    date: "Updated 15 day ago",
  },
  {
    title: "design-system",
    type: "Public",
    lang: "React",
    size: "7320 KB",
    date: "Updated 1 day ago",
  },
  {
    title: "codeant-ci-app",
    type: "Private",
    lang: "Javascript",
    size: "5871 KB",
    date: "Updated 2 days ago",
  },
  {
    title: "analytics-dashboard",
    type: "Private",
    lang: "Python",
    size: "4521 KB",
    date: "Updated 5 days ago",
  },
  {
    title: "mobile-app",
    type: "Public",
    lang: "Swift",
    size: "3096 KB",
    date: "Updated 3 days ago",
  },
  {
    title: "e-commerce-platform",
    type: "Private",
    lang: "Java",
    size: "6210 KB",
    date: "Updated 6 days ago",
  },
  {
    title: "blog-website",
    type: "Public",
    lang: "HTML/CSS",
    size: "1876 KB",
    date: "Updated 4 days ago",
  },
  {
    title: "social-network",
    type: "Private",
    lang: "PHP",
    size: "5432 KB",
    date: "Updated 7 days ago",
  },
  {
    title: "personal-portfolio",
    type: "Private",
    lang: "NextJS",
    size: "7320 KB",
    date: "Updated 15 day ago",
  },
  {
    title: "personal-portfolio",
    type: "Private",
    lang: "NextJS",
    size: "7320 KB",
    date: "Updated 15 day ago",
  },
];
